#!/bin/bash

#@author: marco biondi
#set -e
DOCTEST_SUITE_FRAMEWORK=${0%/*}

# Text color variables
txtunderline=$(tput -Txterm-color sgr 0 1)          # Underline
txtbold=$(tput -Txterm-color bold)             # Bold
txtred=$(tput -Txterm-color setaf 1) #  red
txtgreen=$(tput -Txterm-color setaf 1) #  red
txtblue=$(tput -Txterm-color setaf 4) #  blue
txtwhite=$(tput -Txterm-color setaf 7) #  white
txtgreen=$(tput -Txterm-color setaf 2) #  white
txtorange=$(tput -Txterm-color setaf 3) #  white
txtreset=$(tput -Txterm-color sgr0)             # Reset
info=${bldwht}*${txtrst}        # Feedback
pass=${bldblu}*${txtrst}
warn=${bldred}*${txtrst}

export DOCTEST_COVERAGE=


ADDPARAMS=""
FILES=""
#if [ "$1" != "" ]; then
	if test -d "$1"; then
		FILES=$(find -H $1 -type f -name "*.php" -exec grep -H -l -m 1 '<code>' {} \; )
	else	
		dep=""
		cov=""
		for ((a=1; a <= $# ; a++))
		do
			nome=$(eval echo \${$a})
			if ! test -f "$nome"
			then 
				if echo "$nome" | grep -v "^-";then
					echo "svn status "$nome""
					if svn status "$nome" |grep "^D";then
						echo "$nome cancellato su svn"
						FILES="$FILES $nome"
					fi
				fi

				if [ "$nome" == "-h" ];then 
					echo "Usage: $0 <params> file1... fileN "
					echo
					echo "Params:"
					echo "-dep 		Found and execute impacted doctest"
					echo "-coverage 	Force coverage activation"
					echo "-nc 		Force coverage Deactivation"
					echo "-t 		Filter executed doctest from exact test name"
					exit
				fi
				if [ "$nome" == "-dep" ];then dep="on";continue;fi
				if [ "$nome" == "-coverage" ];then echo "attivo il coverage";export DOCTEST_COVERAGE="on";cov="on";continue;fi
				if [ "$nome" == "-nc" ]
				then 
					unset DOCTEST_COVERAGE
					export DOCTEST_COVERAGE 
					continue
				fi
				if [ "$nome" == "-t" ]
				then 
					unset DOCTEST_COVERAGE
					export DOCTEST_COVERAGE
				fi

				if echo $nome |grep "^-" &>/dev/null
				then
					ADDPARAMS="$ADDPARAMS $nome"
				else
					ADDPARAMS="$ADDPARAMS "$nome" "
				fi
			else
				#if grep -q -H -l -m 1 '<code>' $nome
				#then
				FILES="$FILES $(readlink -f "$nome" 2>/dev/null)"
				#fi
			fi
		done

		if [ "$dep" == "on" ]
		then
			CHECKFILES=$FILES
			for filename in $CHECKFILES
			do
				for depdoctestfile in $(php lib-test/coverage_helper.php --dep-list $filename)
				do
					if ! echo $FILES| grep $depdoctestfile;then
						FILES="$FILES $depdoctestfile "
					fi
				done
			done
		fi
	fi
#else
	if [ "$FILES" == "" ];then
		echo "FILES VUOTO"
		if [ "$cov" != "on" ]
		then
			unset DOCTEST_COVERAGE
			export DOCTEST_COVERAGE
		fi
		cd $DOCTEST_SUITE_FRAMEWORK
		FILEF=$(find -H . -type f -name "*.php" -exec grep -H -l -m 1 '<code>' {} \; )
		for nome in $FILEF
		do
			if grep -q -H -l -m 1 '<code>' $nome;then
				FILES="$FILES $(readlink -f $nome)"
			fi
		done
	fi

#fi

echo
if test -n "$DOCTEST_COVERAGE";then
	echo $txtbold
	echo -n "Coverage"
	echo $txtgreen
	echo " active"
	#if test -z "$1" && test -n "$DOCTEST_COVERAGE";then
	if test -z $FILES ;then
        echo "Clean coverage data..."
        php lib-test/coverage_helper.php --flush-all
	else
		for filename in $FILES
		do
            echo "Clean coverage data for $filename..."
            php lib-test/coverage_helper.php --remove $filename
		done	
	fi
	echo $txtreset
fi
echo

if ! phpdt $ADDPARAMS --template-code=$DOCTEST_SUITE_FRAMEWORK/lib-test/doctestEnv/atk.doctest.tmpl.php $FILES
then
	exit 1
fi

if test -n "$DOCTEST_COVERAGE";then
	echo 
        echo $txtbold
        echo $txtgreen
	echo "Code coverage" 
	echo "-------------" 
	echo $txtreset

	for nome in $FILES
	do
        php lib-test/coverage_helper.php --update $nome
	done
    echo
    echo 'Coverage: ' $(php lib-test/coverage_helper.php -c) '%'
	echo
fi

echo $txtreset

php lib-test/coverage_helper.php --save
